### PR TITLE
Composer support prep work

### PR DESCRIPTION
**Pull request by philwareham**
Hi there,

I want to use this plugin via Composer for the upcoming Textpattern.com website. This pull request starts that process.

You'll then need to:

1. Go to https://packagist.org, register an account (you can use your GitHub credentials) and then submit your Composer package here: https://packagist.org/packages/submit
2. Follow the instructions at foot of page here https://packagist.org/about to hook the Packagist service into your GitHub repo.
3. Unrelated: please go to your repo settings and turn of wiki tab and turn on issues tab.
4. Tag a release (version 0.3.6). I can tag a release for you if you give me collaborator access to your repo.
5. I've removed the compiled `txt` files from the repo - those should be attached to the releases as binaries - again I can do that with repo collab access.

### CODE REVIEW

**Comment by philwareham** [comment]
Bump?

**Comment by cara-tm** [comment]
Thank you lot Phil.
No time for the moment. I will check this later.
;)

**Review by cara-tm — APPROVED** [review]

**Comment by philwareham** [comment]
You could have merged the pull request instead of replicating the changes within. :)

Thanks for the repo access. You would still need to register at Packagist though as only the repo owner can create the hooks needed. See instructions above.

**Comment by cara-tm** [comment]
Hooks created and fonctional ;)

**Pull request merged**
