### PR TITLE
Tidy up

### PR DESCRIPTION
**Pull request by philwareham**

### CODE REVIEW

**Comment by philwareham** [comment]
Cheers. Did Michael Pate not want the amends pull requested back to his original plugin? If not then you might want to re-prefix this plugin to avoid confusion and add GitHub Topic Tags 'textpattern' and 'textpattern-plugin' on this repo?

**Comment by cara-tm** [comment]
Thank you.

**Comment by michaelkpate** [comment]
I really would be happy if cara-tm just went ahead and did a full fork/new version. The combination of power and complexity in this version is far beyond what I came up with.

**Comment by cara-tm** [comment]
Ok. I'll change this plugin version with my prefix.

**Comment by philwareham** [comment]
Cool. I'd suggest putting the various versions into proper GitHub releases and release tags too instead of leaving them loose in the repo. Users should really be using the latest version as a default.

**Comment by philwareham** [comment]
By the way, I'm using this plugin on the new Textpattern official site which will be launching in the not too distant future. Works well. Will obviously credit you both on the contributors page.

**Comment by cara-tm** [comment]
Done: https://github.com/cara-tm/pat_if_amp

**Pull request merged**
